---
- name: exo1
  hosts: test
  become: true
  tasks:
    - name: creer repertoire
      ansible.builtin.file:
        path: /home{{item}}
        state: directory
      loop: [ 1,2,3,4,5,6,7,8,9 ]
    - name: creer repertoire
      ansible.builtin.file:
        path: /auto
        state: directory
    - name: creer un lien
      ansible.builtin.file:
        src: /home{{item}}
        dest: /auto/home{{item}}
        state: link
      loop: "{{ range(1, 9+1, 1) |list }}"

