---
- name: exo3
  hosts: test
  become: true
  tasks:
    - name: creer user
      ansible.builtin.user:
        name: fab
        comment: fab

    - name: create cron
      ansible.builtin.cron:
        user: fab
        name: "test cron"
        minute: "{{ (ansible_date_time.minute|int  + 1) % 60 }}"
        job: date >> /tmp/testcron.txt


