---
- name: exo4
  hosts: test
  become: true
  tasks:
    - name: copier le fichier
      ansible.builtin.copy:
        src: rsyslog.conf
        dest:  /etc/rsyslog.d/30-test.conf
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"
      notify: 
        - reset_rsyslog
        - test_syslog

  handlers:
    - name: reset_rsyslog
      ansible.builtin.service:
        name: rsyslog
        state: restarted
    - name: test_syslog
      community.general.syslogger:
        msg: 'test rsyslog'
        facility: local4
        priority: info

